#!/usr/bin/env python3

# Standard library imports
from random import randint, choice as rc
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app import app
from models import db, Fish, Fishtank, FishSpeciesTank, User, Review
from config import bcrypt
# from faker import Faker
# Remote library imports
if __name__ == '__main__':
    
   
    with app.app_context():

        print("Deleting data...")
        db.session.query(Fish).delete()
        db.session.query(Fishtank).delete()
        db.session.query(FishSpeciesTank).delete()
        # db.session.query(User).delete()
        db.session.query(Review).delete()

        print('Starting seed...')

        print("Creating Fish...")
        fish1 = Fish(species = 'Arowana' , price = 160, tank_size = '250G', water_preference = 'Freshwater', temperature_preference = '75-86', aggressiveness = 'high', life_expectancy = '10 - 15 years', image = 'https://cdn.shopify.com/s/files/1/1980/0633/products/silver-arowana.jpg?v=1627400936', description = 'Arowanas are large and majestic freshwater fish that require proper care for their well-being. Providing a spacious tank, maintaining clean water with proper filtration, offering a balanced diet of live or frozen foods, creating a well-decorated tank with hiding spots, regulating temperature and lighting, being cautious with tank mates, handling with care, and regularly monitoring for signs of illness are essential aspects of taking care of Arowanas. By ensuring these key factors are met, you can help your Arowana thrive in captivity and enjoy a healthy and fulfilling life.')
        fish2 = Fish(species = 'Discus' , price = 60, tank_size = '75G', water_preference = 'Freshwater', temperature_preference = '82-84', aggressiveness = 'moderate', life_expectancy = '10 years', image = 'https://tackleboxbabe.com/wp-content/uploads/2023/01/HDimg-Launch2020-16.jpg', description="Discus fish are popular freshwater fish known for their striking appearance and unique behavior. They require a spacious tank with clean, warm water, soft and slightly acidic. They are omnivorous, needing a balanced diet of pellets, frozen/live foods, and vegetable matter. Discus fish are social and prefer to be kept in groups of 5 or more in a heavily planted tank with hiding spots. Regular monitoring of water parameters, nutrition, and providing a suitable environment are crucial for their health and well-being.")
        fish3 = Fish(species = 'Corydoras' , price = 6.99, tank_size = '20G', water_preference = 'Freshwater', temperature_preference = '72-82', aggressiveness = 'low', life_expectancy = '5 years', image = 'https://corycatfish.com/wp-content/uploads/2020/12/Albino_Cory_Cat-min-2.jpg', description="Corydoras, also known as Cory Catfish or Cory Cats, are small, peaceful freshwater fish that are popular among aquarium enthusiasts. They are known for their adorable appearance and unique behavior, making them a fascinating addition to any aquarium. Corydoras are bottom-dwelling fish that thrive in a well-maintained tank with soft, slightly acidic water and sandy substrate. They are omnivorous and will eat a variety of foods, including sinking pellets, frozen/live foods, and small bits of vegetables. Corydoras are social fish and should be kept in groups of at least 5 to allow them to exhibit their natural schooling behavior. They are generally peaceful and can be kept with other non-aggressive fish species. Regular water changes, proper filtration, and a suitable environment with hiding spots are important for their overall health and well-being. Corydoras are relatively hardy and make great additions to community aquariums, adding a playful and entertaining aspect to the tank.")
        fish4 = Fish(species = 'Plecostomus' , price = 40, tank_size = '150G', water_preference = 'Freshwater', temperature_preference = '75-82', aggressiveness = 'low', life_expectancy = '10 - 15 years', image = 'https://fishkeepingfans.com/wp-content/uploads/2021/08/Bristlenose-Pleco.jpg', description=" Plecostomus, often referred to as Plecos, are a popular type of catfish known for their unique appearance and algae-eating habits. They are commonly kept in freshwater aquariums as they are known to help control algae growth. Plecos are typically nocturnal and spend much of their time scavenging for food, including algae, leftover fish food, and small invertebrates. They have a flattened body shape, a sucker-like mouth, and a large, fan-shaped dorsal fin that adds to their distinctive appearance. Plecos can vary in size, with some species reaching over a foot in length, so it's important to provide them with ample swimming space and hiding spots in the tank. They prefer well-oxygenated water and a varied diet that includes a mix of algae-based and protein-rich foods. It's essential to be mindful of their specific dietary needs and tank requirements, as different species of Plecos may have different preferences. Regular water changes, adequate filtration, and monitoring of water parameters are also important for their health and well-being. Plecos are generally peaceful, but they can become territorial, especially when they are mature, so it's important to provide them with enough space and suitable tank mates. With proper care, Plecos can thrive in a freshwater aquarium, adding a unique and interesting element to the tank.")
        fish5 = Fish(species = 'Glass Catfish' , price = 8.99, tank_size = '30G', water_preference = 'Freshwater', temperature_preference = '75-80', aggressiveness = 'low', life_expectancy = '7 - 8  years', image = 'https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQ7dd3DqMQY2cw6oZXl6TjsRJXs8EHwZcit9aMQLOBUbaHuZEuFLBvOinfuHDzWPk7EsMxMxLkFouz5L28', description=" Glass catfish, or Kryptopterus bicirrhis, are a fascinating and peaceful species of fish found in Southeast Asia. They have a translucent appearance that allows you to see their internal organs and a pair of long barbels on their mouth. Glass catfish are primarily carnivorous and prefer a well-planted tank with hiding spots and open swimming space. They are known for their synchronized swimming behavior in shoals and require good water quality and subdued lighting conditions. With proper care, glass catfish can make a captivating addition to any freshwater aquarium.")
        fish6 = Fish(species = 'Scissortail Rasbora' , price = 13.99 , tank_size = '30G', water_preference = 'Freshwater', temperature_preference = '77-82', aggressiveness = 'low', life_expectancy = '4-7 years', image = 'https://www.fishkeepingworld.com/wp-content/uploads/2022/03/Scissortail-Rasbora-tankmates.jpg?ezimgfmt=rs:372x279/rscb10/ngcb10/notWebP', description="The Scissortail Rasbora, or Rasbora trilineata, is a popular and attractive species of fish that hails from Southeast Asia. They are known for their striking appearance, with a silvery body adorned with three horizontal black lines and a deeply forked tail, resembling a pair of scissors. Scissortail Rasboras are peaceful and social fish that do best in groups, and they make excellent community fish for a well-planted freshwater aquarium. They prefer soft, slightly acidic water and thrive in a tank with ample swimming space and hiding spots. Scissortail Rasboras are omnivorous and will readily accept a variety of foods, including flakes, pellets, and live or frozen foods. With their active and playful nature, Scissortail Rasboras can add vibrancy and movement to any aquarium setting.")
        fish7 = Fish(species = 'Flowerhorn' , price = 180, tank_size = '75G', water_preference = 'Freshwater', temperature_preference = '80-85', aggressiveness = 'high', life_expectancy = '10-12 years', image = 'https://www.hepper.com/wp-content/uploads/2023/02/flowerhorn-cichlid-in-aquarium_luis2499-Shutterstock.jpg', description=" The Flowerhorn fish is a sought-after species known for its unique appearance and behavior. Originating from Malaysia and Taiwan, Flowerhorns have a distinctive look with a protruding forehead, vibrant colors, and intricate patterns. However, they are also controversial due to being a hybrid species created through selective breeding. Flowerhorns are known for their aggressive behavior and territorial nature, requiring specific care in a large tank with proper water parameters and a balanced diet. Responsible ownership and research into their care requirements are important for their health and welfare.")
        fish8 = Fish(species = 'Tiger shovelnose catfish' , price = 50, tank_size = '180G', water_preference = 'Freshwater', temperature_preference = '75-86', aggressiveness = 'low', life_expectancy = '18 - 25 years', image = 'https://aquadiction.world/img/profile/1037-tiger-shovelnose-catfish.jpg', description="The Tiger Shovelnose Catfish, also known as the Zorro Catfish or the Denticulated Catfish, is a unique and fascinating species native to South America's Amazon Basin. As the name suggests, their distinctive feature is a long, slender body with a flattened head resembling a shovel, and striking black and yellow striped pattern on their body and fins. Tiger Shovelnose Catfish are known for their predatory behavior and require a large tank with plenty of swimming space. They are opportunistic feeders and prefer a varied diet of live and frozen foods. However, they can be challenging to care for due to their size, behavior, and specific water requirements. It's essential to provide them with appropriate tank mates, ample hiding spots, and regular water maintenance to ensure their well-being in a home aquarium. Proper research and understanding of their care needs are crucial for keeping Tiger Shovelnose Catfish healthy and thriving in captivity.")
        fish9 = Fish(species = 'Crayfish' , price = 65, tank_size = '10G', water_preference = 'Freshwater', temperature_preference = '64-77', aggressiveness = 'high', life_expectancy = '2 - 3', image = 'https://cdn.shopify.com/s/files/1/1163/2672/products/Imperial-Purple-Crayfish-Small-8_1024x1024.jpg?v=1656632340', description="Crayfish, also known as crawfish or freshwater lobsters, are fascinating crustaceans that are popular in freshwater aquariums. They come in various species, sizes, and colors, making them interesting additions to aquarium setups. Crayfish are known for their unique appearance, with a hard exoskeleton, a pair of large front claws, and a segmented body. They are typically bottom-dwellers and are skilled scavengers, feeding on a wide range of foods including algae, detritus, small invertebrates, and even fish. Crayfish are generally hardy and can tolerate a wide range of water conditions, but they do require adequate hiding spots and a suitable substrate for burrowing. It's essential to provide them with proper nutrition, a well-maintained tank, and compatible tank mates to ensure their well-being. However, it's important to note that crayfish can be territorial and aggressive, and some species may pose a threat to smaller fish or other tank inhabitants. Therefore, careful research and consideration of their care requirements and tank compatibility are necessary when keeping crayfish in an aquarium.")
        fish10 = Fish(species = 'Mudskipper' , price = 20, tank_size = '38G', water_preference = 'Brackish', temperature_preference = '68-78', aggressiveness = 'high', life_expectancy = '5 years', image = 'https://johnhutchingsmuseum.org/wp-content/uploads/2021/03/Atlantic-Mudskipper-Closeup.jpg', description="Mudskippers are unique and fascinating fish that are adapted to live in intertidal areas where land meets water. They are known for their ability to survive in both aquatic and terrestrial environments, making them extraordinary creatures to observe in aquarium setups. Mudskippers have elongated bodies, flattened heads, and pectoral fins modified into powerful legs that allow them to move on land and even climb mangroves and muddy substrates. They are typically small in size and come in various colors, ranging from dull browns to vibrant greens or blues, depending on the species. Mudskippers have specialized gills that allow them to extract oxygen from both air and water, enabling them to breathe in both environments. They are also known for their unique behaviors, such as burrowing in mud, skipping and hopping on land, and displaying territorial and courtship behaviors. Mudskippers are omnivorous, feeding on small insects, crustaceans, algae, and detritus. However, they require a well-maintained tank with access to both water and land areas, as well as appropriate temperature, humidity, and lighting conditions to thrive. Careful consideration of their specific requirements and behaviors is essential for successfully keeping mudskippers in an aquarium setting.")
        fish11 = Fish(species = 'Axolotl', price = 150, tank_size = '30G', water_preference = 'Freshwater', temperature_preference = '64-68', aggressiveness = 'high', life_expectancy = '15 years', image = 'https://cdn.shopify.com/s/files/1/0621/0771/3705/products/image_dedc5981-899b-4e63-b0bf-98c10efcc6ab.jpg?v=1680374259&width=600', description="Axolotls, also known as Mexican salamanders or water monsters, are unique aquatic creatures that belong to the family Ambystomatidae. They are renowned for their regenerative abilities and neotenic traits, which means they retain their juvenile characteristics throughout their adult lives. Axolotls have elongated bodies, feathery external gills, and lidless eyes that give them a distinct appearance. They come in a wide range of colors, including shades of black, brown, albino, and piebald, making them popular as pets in the aquarium trade. Axolotls are fully aquatic, and they require a tank with cool, clean water and hiding spots such as caves or plants. They are carnivorous, feeding on live or frozen food such as small fish, insects, and worms. One of the unique features of axolotls is their remarkable ability to regenerate lost body parts, including limbs, spinal cord, and even parts of their heart and brain. This regenerative ability makes them a subject of scientific research and fascination among hobbyists. However, axolotls require specific care, including appropriate water quality, temperature, and diet, as well as ample space and hiding spots, to thrive in captivity. Axolotls are also considered endangered in the wild due to habitat loss and pollution, making responsible and ethical captive breeding and care of these fascinating creatures essential for their conservation.")
        fish12 = Fish(species = 'pipa pipa toad' , price = 60, tank_size = '20G', water_preference = 'Freshwater', temperature_preference = '70-75', aggressiveness = 'low', life_expectancy = '7 years', image = 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Pipa_pipa01.jpg', description=" Pipa pipa toads, also known as Surinam toads or leaf frogs, are unique amphibians that require a well-maintained aquatic environment, including clean water, appropriate filtration, and a varied diet of live or frozen foods. They are known for their flattened bodies, camouflaged appearance, and unique reproductive strategy where the female lays eggs on the male's back. Proper care and monitoring of their aquatic environment are crucial, and consulting with experienced amphibian keepers or veterinarians is recommended.")
        fish13 = Fish(species = 'Siamese fighting fish' , price = 25, tank_size = '5G', water_preference = 'Freshwater', temperature_preference = '75-80', aggressiveness = 'high', life_expectancy = '2-5 years', image = 'https://home.adelphi.edu/~ve21375/betta%20fish%20home%201.jpg', description="Beta fish, also known as Siamese fighting fish, are popular aquarium fish known for their vibrant colors and flowing fins. They require a well-maintained aquarium with proper water temperature and quality, as well as appropriate tank size and decorations for stimulation. Betta fish are carnivorous and need a varied diet that includes high-quality betta pellets or flakes, as well as occasional live or frozen foods. They are solitary fish and should be housed alone to prevent aggression towards other fish. Regular water changes, monitoring for signs of illness, and providing adequate hiding places are important aspects of caring for betta fish. It's also essential to avoid overcrowding and provide proper filtration to maintain water quality. Consulting with experienced betta fish keepers or veterinarians can provide further guidance on their care and well-being.")
        fish14 = Fish(species = 'Black Ghost Knifefish' , price = 20, tank_size = '180G', water_preference = 'Freshwater', temperature_preference = '75-78', aggressiveness = 'low', life_expectancy = '7 years', image = 'https://www.fishlaboratory.com/wp-content/uploads/2021/11/Black-Ghost-Knife-Fish.jpeg', description="Black ghost knifefish, also known as Apteronotus albifrons, are unique and fascinating fish that are often kept in aquariums by experienced hobbyists. They are known for their distinctive appearance, with a long, slender body and a black or dark brown coloration. Black ghost knifefish are nocturnal and prefer low light environments, and they are known for their ability to navigate using electrolocation due to their specialized sensory organs. They require a large aquarium with hiding places, such as caves or PVC pipes, and a soft substrate to mimic their natural habitat. They are carnivorous and require a varied diet of high-quality pellets, frozen or live foods, and occasional treats like insects or small fish. Regular water changes and water quality monitoring are important for their well-being, as they are sensitive to water parameters. Black ghost knifefish are solitary and can be territorial, so it's important to provide ample swimming space and avoid keeping them with aggressive or territorial tank mates. Consulting with experienced knifefish keepers or veterinarians can provide further guidance on their care and maintenance in an aquarium setting.")
        fish15 = Fish(species = 'Oscar' , price = 10, tank_size = '55G', water_preference = 'Freshwater', temperature_preference = '75-80', aggressiveness = 'high', life_expectancy = '10-20 years', image = 'https://cdn.shopify.com/s/files/1/0311/3149/articles/featured_image_-_oscar_cichlid_fish.jpg?v=1663363956', description="Oscar fish, also known as Astronotus ocellatus, are popular and large cichlids that are commonly kept in aquariums by experienced fishkeepers. They are known for their striking appearance, with a large, oval-shaped body and vibrant colors ranging from red, orange, yellow, to black. Oscar fish are known for their engaging personalities and are often referred to as water puppies due to their playful and interactive behavior. They require a large aquarium with plenty of swimming space and hiding spots, such as caves or PVC pipes, as they can be territorial. Oscars are omnivorous and will eat a varied diet of pellets, flakes, frozen or live foods, and even small feeder fish or insects. They are known to have a hearty appetite and can be messy eaters, so proper filtration and regular water changes are essential for maintaining good water quality. Oscars can grow quite large, reaching up to a foot or more in size, so providing adequate space and tank mates of similar size and temperament is important. They can be aggressive towards smaller or more docile tank mates, so careful consideration should be given to tank mates and aquarium setup")
        fish15 = Fish(species = 'Octopus' , price = 200, tank_size = '75G', water_preference = 'Saltwater', temperature_preference = '59-61', aggressiveness = 'high', life_expectancy = '1-5 years', image = 'https://squeaksandnibbles.com/wp-content/uploads/2022/04/octopus-SN-long.jpg', description="Owning an octopus as a pet is a unique and challenging endeavor that requires specialized knowledge and experience. Octopuses are highly intelligent and fascinating creatures known for their complex behaviors and remarkable ability to change color and shape. They require a large and secure aquarium with ample hiding places, such as caves or crevices, as they are naturally skilled at escaping and exploring their environment. Octopuses are also skilled hunters, requiring a varied diet of live or frozen foods, such as crustaceans, mollusks, and small fish, to meet their nutritional needs. Water quality and temperature must be closely monitored and maintained within appropriate ranges, as octopuses are sensitive to changes in water chemistry. Octopuses are also known for their curiosity and problem-solving abilities, which may require careful consideration of the tank's design and equipment to prevent escapes or damage. Additionally, octopuses have relatively short lifespans and complex care requirements, making them suitable for experienced and dedicated aquarists who can provide the necessary conditions for their well-being. It is important to research and understand the specific needs and requirements of the octopus species being kept, and consult with experienced octopus keepers or marine biologists for guidance on providing optimal care for these unique and intriguing creature")
        fish16 = Fish(species = 'Dragon Eel' , price = 800, tank_size = '180G', water_preference = 'Saltwater', temperature_preference = '65-78', aggressiveness = 'high', life_expectancy = '25-30 years', image = 'https://www.learnaboutnature.com/wp-content/uploads/Dragon-Moray-Eel.jpg', description="Owning a Dragon Eel as a pet can be a challenging and rewarding experience. Dragon Moray Eels, also known as Dragon Eels or Ribbon Eels, are known for their striking appearance and unique behaviors. They have elongated bodies with a long, thin ribbon-like tail, and their bodies are often brightly colored, with a distinctive pattern that resembles the scales of a dragon. Dragon Moray Eels require a large aquarium with plenty of hiding places, such as caves or PVC pipes, as they are secretive and nocturnal creatures that spend much of their time hiding in the substrate or rockwork. They are carnivorous and require a varied diet of live or frozen foods, such as small fish, crustaceans, and mollusks. Water quality and temperature must be closely monitored and maintained within appropriate ranges, as Dragon Moray Eels are sensitive to changes in water chemistry. They also require a secure lid or cover on the tank to prevent escapes, as they are known to be skilled jumpers. Additionally, Dragon Moray Eels can be aggressive towards tank mates, and careful consideration should be given to tank mates and their compatibility. It is important to research and understand the specific needs and requirements of Dragon Moray Eels, and consult with experienced eel keepers or marine biologists for guidance on providing optimal care for these unique and captivating creatures.")
        fish17 = Fish(species = 'Bobbit Worm' , price = 500, tank_size = '500G', water_preference = 'Saltwater', temperature_preference = '65-78', aggressiveness = 'high', life_expectancy = '3-5 years', image = 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Eunice_aphroditois.jpg', description="Bobbit Worms, also known as Eunice aphroditois, are marine worms known for their predatory nature and impressive hunting abilities. They are usually found in tropical and subtropical waters, and they have a distinctive appearance with long, slender bodies and sharp jaws that they use to capture prey. Bobbit Worms are typically kept in species-specific aquariums, as they can be aggressive towards tank mates and may pose a threat to smaller or slower-moving fish. They require a well-established marine aquarium with appropriate substrate, rockwork, and hiding places for them to burrow and ambush prey. Bobbit Worms are opportunistic hunters that will actively search for food and may consume a variety of live or frozen foods, such as small fish, crustaceans, and worms. Water quality and temperature should be maintained within appropriate ranges, and regular monitoring is necessary to ensure the health and well-being of the Bobbit Worm. It is important to handle Bobbit Worms with caution, as they can deliver a painful bite with their sharp jaws. Due to their specialized needs and predatory nature, owning a Bobbit Worm requires advanced knowledge and experience in marine aquarium keeping. Proper research, consultation with experienced aquarists, and adherence to local regulations are essential for providing optimal care for these unique and intriguing creatures.")
        fish18 = Fish(species = 'Spiny box burrfish' , price = 45, tank_size = '180G', water_preference = 'Saltwater', temperature_preference = '68-78', aggressiveness = 'semi', life_expectancy = '5-8 years', image = 'https://assets.petco.com/petco/image/upload/f_auto,q_auto/3467790-center-1', description="Spiny Box Burrfish, also known as Chilomycterus antillarum, are marine fish known for their unique appearance and intriguing behavior. They are usually found in the Western Atlantic Ocean and the Caribbean Sea, and they have a distinctive box-like shape with a thick, tough skin covered in spines that they use for defense. Spiny Box Burrfish are typically kept in marine aquariums with appropriate tank size, water quality, and temperature parameters. They require a well-established aquarium with hiding places, as they are known to be shy and may spend much of their time hiding in crevices or among rockwork. Spiny Box Burrfish are carnivorous and typically consume a varied diet of live or frozen foods, such as crustaceans, mollusks, and small fish. Care should be taken to provide a balanced and varied diet to meet their nutritional needs. Spiny Box Burrfish are known for their unique feeding behavior, which involves grinding their beak-like teeth together to crack open the shells of their prey. Water quality should be regularly monitored and maintained within appropriate ranges to ensure the health and well-being of the Spiny Box Burrfish. It is important to handle Spiny Box Burrfish with caution, as their spines can cause injury. Due to their specialized needs and unique characteristics, owning a Spiny Box Burrfish requires knowledge and experience in marine aquarium keeping. ")
        fish19 = Fish(species = 'Mantis Shrimp' , price = 138, tank_size = '10G', water_preference = 'Saltwater', temperature_preference = '72-80', aggressiveness = 'high', life_expectancy = '20 years', image = 'https://aquariumbreeder.com/wp-content/uploads/2020/01/Mantis-shrimp-logo.jpg', description="Mantis shrimp, also known as stomatopods, are unique and colorful marine creatures that are known for their incredible hunting abilities and striking appearance. They come in various species, each with their own distinct characteristics and behaviors. Mantis shrimp are known for their powerful claws, which they use to catch prey and defend themselves. They are also known for their complex eyes, which are among the most advanced in the animal kingdom. Mantis shrimp are highly intelligent and curious creatures, making them intriguing pets for experienced and dedicated marine hobbyists. However, they require a specialized environment and proper care to thrive, as they can be aggressive and have specific dietary and housing needs. Proper research, preparation, and understanding of mantis shrimp behavior and care requirements are essential before considering them as a pet. Nonetheless, for those who are willing to provide the appropriate care and attention, owning a mantis shrimp can be a unique and rewarding experience.")
        fish20 = Fish(species = 'Starfish' , price = 35, tank_size = '125G', water_preference = 'Saltwater', temperature_preference = '72-78', aggressiveness = 'low', life_expectancy = '35 years', image = 'https://www.fantaseaaquariums.com/wp-content/uploads/2022/05/Aquarium-starfish.jpg', description="Starfish, also known as sea stars, are intriguing marine creatures with their distinct shape and interesting behaviors. They come in various species, each with its own unique characteristics and requirements. Starfish are known for their ability to regenerate limbs, which makes them a fascinating species to observe and learn about. They are typically slow-moving and peaceful creatures, making them suitable for aquariums with other marine life. Starfish are omnivorous, and their diet typically consists of algae, small invertebrates, and detritus. They require a marine aquarium with appropriate water parameters and a varied diet to thrive. Starfish also need a suitable substrate and hiding places in the tank for them to explore and rest.")
        fish21 = Fish(species = 'Redtail catfish' , price = 24, tank_size = '2000G', water_preference = 'Freshwater', temperature_preference = '68-80', aggressiveness = 'mild', life_expectancy = '15 years', image = 'https://fishkeepingfans.com/wp-content/uploads/2021/10/Redtail-Catfish-2.jpg', description="Red tail catfish, scientifically known as Phractocephalus hemioliopterus, are large and powerful predatory fish that are native to South America. They are known for their striking appearance, with a red tail fin that contrasts against their dark body coloration. Red tail catfish can grow to a considerable size, reaching over 3 feet in length, and require a spacious aquarium with ample swimming space. They are primarily piscivorous, meaning they primarily feed on other fish, but they can also eat a varied diet that includes pellets, live or frozen foods, and even small mammals. Red tail catfish are known for their active and curious nature, and they require a well-maintained aquarium with appropriate filtration and water quality parameters. They can be kept with other large, compatible species, but tank mates should be chosen carefully to avoid aggression or predation. Due to their size and dietary requirements, owning a red tail catfish requires careful consideration of tank size, diet, and tank mates, as well as a commitment to regular maintenance and care. However, for experienced and dedicated aquarium keepers, owning a red tail catfish can be a thrilling and captivating experience.")
        fish22 = Fish(species = 'Blue Tang' , price = 100, tank_size = '180G', water_preference = 'Saltwater', temperature_preference = '73-82', aggressiveness = 'Mild', life_expectancy = '8-20 years', image = 'https://www.americanoceans.org/wp-content/uploads/2021/01/blue-tangs-1-scaled.jpg', description="Owning blue tangs can be a rewarding experience for saltwater aquarium enthusiasts. Blue tangs, also known as Paracanthurus hepatus, are known for their stunning bright blue coloration and sleek body shape. They are commonly recognized as the character Dory from the popular movie Finding Nemo. Blue tangs are relatively small fish, reaching an average size of 12-15 centimeters (5-6 inches) in captivity. They are herbivorous, primarily feeding on algae and plant-based foods in the wild, and require a varied diet that includes a combination of flakes, pellets, frozen, and fresh foods in captivity. Blue tangs are known for their active swimming behavior and can be a striking addition to a well-maintained saltwater aquarium with appropriate tank size, water quality, and filtration. They are generally peaceful, but can become territorial and aggressive towards other tang species or fish with similar body shape/coloration. Therefore, careful consideration of tank mates and adequate hiding spaces is important. Blue tangs also require a stable environment with consistent water parameters, including temperature, salinity, and pH. It's important to note that blue tangs are considered to be more challenging to care for due to their specific dietary requirements and sensitivity to water quality, and they are best suited for experienced saltwater aquarium keepers who are committed to providing the appropriate care and attention they need. With proper care and attention, blue tangs can thrive in a well-maintained saltwater aquarium and provide their owners with hours of enjoyment observing their beauty and unique behaviors.")
        fish23 = Fish(species = 'Clownfish' , price = 20, tank_size = '30G', water_preference = 'Saltwater', temperature_preference = '75-80', aggressiveness = 'high', life_expectancy = '3-5 years', image = 'https://www.fantaseaaquariums.com/wp-content/uploads/2020/03/clownfish.jpg', description="Clownfish are known for their bright colors, unique patterns, and interesting behaviors. They are typically small-sized fish, with different species reaching various sizes ranging from 2 to 6 inches. Clownfish are known to form a symbiotic relationship with sea anemones, where they live among the tentacles and gain protection while providing food for the anemone. However, in a home aquarium, clownfish can thrive without the presence of anemones, as they can adapt to other hiding places like coral reefs or rock structures. Clownfish are omnivorous, feeding on a varied diet that includes flakes, pellets, frozen, and live foods. They are generally peaceful and can be kept in a community aquarium with other compatible species. Clownfish are also known for their interesting behaviors, such as their unique swimming patterns and territorial defense of their preferred nesting site. They are relatively hardy and easy to care for, making them suitable for beginner and experienced marine aquarium keepers alike. It's important to provide a suitable tank size, appropriate water parameters, and regular maintenance to ensure the health and well-being of clownfish. With proper care, clownfish can thrive in a well-maintained marine aquarium and provide their owners with hours of enjoyment observing their playful antics and vibrant colors.")
        fish24 = Fish(species = 'Weedy sea dragon ' , price = 3499, tank_size = '180G', water_preference = 'Saltwater', temperature_preference = '68', aggressiveness = 'low', life_expectancy = '5-7 years', image = 'https://i.natgeofe.com/n/97762bed-8c67-4130-a050-9243d9cf403f/weedy-sea-dragon_3x4.jpg', description="Weedy sea dragons are mesmerizing and unusual creatures that closely resemble floating seaweed or kelp, making them a fascinating addition to a marine aquarium. They are native to the coastal waters of southern Australia and are known for their ornate, leaf-like appendages that provide them with excellent camouflage. Weedy sea dragons require a carefully maintained aquarium environment that mimics their natural habitat, including a temperate or cold-water tank with ample hiding places, live rock, and gentle water flow. They are strict carnivores, feeding on small crustaceans and other small marine animals, and their diet needs to be carefully balanced to provide the necessary nutrients. Weedy sea dragons can be delicate and require experienced aquarists to ensure their well-being. They are best suited for experienced marine aquarium keepers who are willing to provide the necessary care and attention to maintain their unique needs. Proper husbandry, regular water quality testing, and careful monitoring are essential to ensure the health and well-being of weedy sea dragons in captivity. With appropriate care, weedy sea dragons can thrive and become a captivating centerpiece in a marine aquarium, offering a unique and visually stunning display for their owners and admirers alike.")
        fish25 = Fish(species = 'Black diamond stingray' , price = 650, tank_size = '265G', water_preference = 'Freshwater', temperature_preference = '68-88', aggressiveness = 'low', life_expectancy = '19 - 28 years', image = 'https://reefbuilders.com/wp-content/blogs.dir/1/files/2011/03/black-diamond-stingray.jpg',description=" Black diamond stingrays are large, exotic, and unique species of stingrays known for their striking black coloration with white diamond-shaped markings on their disc. They are native to the rivers of South America and require specific care to thrive in captivity. Black diamond stingrays need a spacious tank with soft sandy substrate, hiding spots, and a carefully maintained water quality, including temperature, pH, and water hardness that mimics their natural habitat. They are carnivorous and prefer a diet of live or frozen foods such as shrimp, fish, and worms. Providing a well-balanced and varied diet is crucial for their health and growth. Black diamond stingrays are known for their strong personalities and can be territorial, so careful tank mates selection is essential. Due to their large size and complex care requirements, they are recommended for experienced aquarists with ample space and resources to provide for their needs. Regular monitoring of water parameters, diligent tank maintenance, and a good understanding of their behavior and health requirements are essential to successfully keep and care for black diamond stingrays in captivity. However, with proper care and attention, black diamond stingrays can be captivating and fascinating additions to a dedicated and well-maintained freshwater aquarium.")
        fish26 = Fish(species = 'Lionfish' , price = 100, tank_size = '38G', water_preference = 'Saltwater', temperature_preference = '68-78', aggressiveness = 'high', life_expectancy = '10 years', image = 'https://www.worldlifeexpectancy.com/images/a/w/b/pterois-volitans/pterois-volitans.jpg', description="Owning a lionfish can be a rewarding experience for experienced marine aquarium keepers. Lionfish, also known as Pterois species, are known for their striking appearance with vibrant colors, unique fin arrangements, and venomous spines. They are native to the tropical and subtropical waters of the Indo-Pacific region and are known for their predatory behavior and ability to adapt to various marine environments. Lionfish require a well-maintained marine aquarium with appropriate tank size, high-quality water conditions, and ample hiding spots. They are carnivorous and typically feed on a diet of small fish and crustaceans, so providing a varied and nutritionally balanced diet is crucial for their health. Lionfish are also known for their solitary nature and may not tolerate tank mates well, so careful consideration of tank mates selection is necessary. Additionally, handling lionfish requires caution due to their venomous spines, and proper safety measures should be taken when interacting with them. Regular monitoring of water parameters, diligent tank maintenance, and careful observation of their behavior and health are important for successful lionfish keeping. It's also important to note that some species of lionfish are invasive in certain areas and may have legal restrictions on ownership. Therefore, thorough research, preparation, and adherence to local regulations are essential for responsible lionfish ownership. With proper care, attention, and understanding of their specific needs, lionfish can make stunning additions to a well-maintained marine aquarium.")
        fish27 = Fish(species = 'Angelfish' , price = 25, tank_size = '70G', water_preference = 'Freshwater', temperature_preference = '77-82', aggressiveness = 'low', life_expectancy = '5 years', image = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Group_of_Pterophyllum_Altum.jpg/800px-Group_of_Pterophyllum_Altum.jpg',description="Angelfish, also known as Pterophyllum species, are known for their graceful and elegant appearance with their distinctive triangular body shape, long flowing fins, and striking colors. They are native to the Amazon River basin in South America and are popular choices for community aquariums. Angelfish require a well-maintained aquarium with appropriate tank size, water temperature, pH, and water quality to thrive. They prefer a heavily planted tank with plenty of hiding spots and swimming space. Angelfish are omnivorous and typically feed on a varied diet of flakes, pellets, live, and frozen foods. Providing a balanced and nutritious diet is essential for their health and vitality. Angelfish are generally peaceful but can be territorial during breeding or when establishing dominance, so careful consideration of tank mates selection is necessary. They can also exhibit interesting behaviors, such as pair bonding and mouth brooding during breeding. Regular water parameter monitoring, tank maintenance, and attention to their behavior and health are crucial for successful angelfish keeping. It's also important to note that angelfish may have specific breeding requirements, and breeders may choose to keep them in a separate breeding setup.")
        fish28 = Fish(species = 'Colombian Shark Catfish' , price = 16, tank_size = '350G', water_preference = 'Brackish', temperature_preference = '75-80', aggressiveness = 'low', life_expectancy = '10-15 years', image = 'https://www.aquariumsource.com/wp-content/uploads/2022/07/cs.jpg', description="Colombian Shark Catfish, also known as Loricaria colombian, are interesting and unique fish that are popular among catfish enthusiasts. They are known for their distinctive appearance with a long, slender body, shark-like appearance, and armored plating on their body. They are native to South America and are typically found in fast-moving rivers and streams with rocky substrates. Colombian Shark Catfish are typically peaceful and can be kept in a community aquarium with compatible tank mates. They prefer a well-maintained aquarium with plenty of hiding spots and caves to mimic their natural habitat. Colombian Shark Catfish are primarily bottom-dwelling and feed on a varied diet of algae, detritus, and small invertebrates. It's important to provide a balanced diet that includes specialized catfish pellets or wafers, as well as occasional live or frozen foods to ensure their nutritional needs are met. These catfish are known to be hardy and adaptable, but they do require good water quality and regular tank maintenance. They may also exhibit interesting behaviors such as scavenging, foraging, and burrowing in the substrate. Overall, Colombian Shark Catfish can make fascinating additions to a catfish or community aquarium, but proper care, tank setup, and attention to their unique needs are essential for their well-being.")
        fish29 = Fish(species = 'Oranda Goldfish' , price = 30, tank_size = '10G', water_preference = 'Freshwater', temperature_preference = '65-72', aggressiveness = 'low', life_expectancy = '8 - 15', image = 'https://petkeen.com/wp-content/uploads/2021/01/Oranda-Goldfish_Nantawat-Chotsuwan_shutterstock.jpg', description=" Oranda Goldfish are a popular and unique type of goldfish known for their distinctive appearance and charming personality. They have a rounded body shape, a prominent head crest or wen, and long flowing fins. The most striking feature of the Oranda Goldfish is their wen, which can grow and develop into a fleshy, warty appearance as they mature. Oranda Goldfish come in a variety of colorations, including red, orange, black, blue, and calico, making them highly sought after by goldfish enthusiasts. They are typically peaceful and can be kept in a well-maintained aquarium or pond with other goldfish species of similar size and temperament. Oranda Goldfish are omnivorous and will eat a varied diet that includes both dry and wet foods, such as pellets, flakes, frozen or live foods, and even some vegetable matter. It's important to provide a balanced diet to ensure their nutrition and health. Oranda Goldfish thrive in a spacious environment with good water quality, ample swimming space, and hiding spots. They are known to be interactive and curious fish, often showing playful and inquisitive behavior. However, their wen can require special care as it may be prone to infections and growth issues, so regular monitoring and maintenance are necessary. Overall, Oranda Goldfish are captivating and rewarding fish to own,")
        fish30 = Fish(species = 'Lungfish' , price = 150, tank_size = '60G', water_preference = 'Freshwater', temperature_preference = '76-86', aggressiveness = 'high', life_expectancy = '100 years', image = 'https://static.scientificamerican.com/sciam/cache/file/EE9CD76A-C71F-45FA-9532AA3A45831B52_source.jpg', description=" Owning a lungfish can be a unique and rewarding experience for fishkeepers who are interested in these prehistoric and fascinating creatures. However, it's important to note that lungfish have specific care requirements that need to be met to ensure their health and well-being. They require a large tank with ample swimming space, as they are active swimmers and can grow quite large depending on the species. They also need a suitable substrate for burrowing, as lungfish are known to burrow in mud or detritus. Additionally, they require high-quality water conditions with proper filtration and regular water changes to maintain optimal water quality. Diet is also important, as lungfish are typically omnivorous and may require a varied diet of live, frozen, and prepared foods. It's also worth noting that lungfish can be escape artists, as they are known to be able to crawl out of tanks, so a securely fitted lid or cover is necessary. Lungfish are known for their unique and intriguing behaviors, such as their ability to breathe air, burrow in substrate, and display interesting feeding habits. Proper research and preparation are key to providing a suitable and thriving environment for owning a lungfish as a pet.")

        fishes = [fish1, fish2, fish3, fish4, fish5, fish6, fish7, fish8,fish9,fish10, fish11,fish12, fish13, fish14, fish15, fish16,fish17,fish18, fish19, fish20, fish21, fish22, fish23, fish24, fish25, fish26, fish27, fish28, fish29, fish30]
            # Seed code goes here!

        print('creating Tanks...')
        Ten = Fishtank(tank_name ='10 Gallon', price = '$10', image ='https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/170917-center-2')
        Twenty = Fishtank(tank_name ='20 Gallon',price = '$20', image ='https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/2773074-center-2')
        Thirty = Fishtank(tank_name ='30 Gallon',price = '$30', image ='https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/2773074-center-2')
        Forty = Fishtank(tank_name ='40 Gallon', price = '$40',image ='https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/170968-center-1')
        Fifty_Five = Fishtank(tank_name ='50 Gallon',price = '$55', image ='https://m.media-amazon.com/images/I/91xmGAbd-yL._AC_SX466_.jpg')
        Seventy = Fishtank(tank_name = '75 five', price = '$75', image ='https://assets.petco.com/petco/image/upload/f_auto,q_auto/660680-center-1')
        HundredAndFifty = Fishtank(tank_name ='125',price = '$125', image='https://m.media-amazon.com/images/I/31xD4YrXtAL._AC_.jpg')
        THREEHUNDRED = Fishtank(tank_name = '300', price = '$300', image= 'https://advancedaquariumconcepts.com/wp-content/uploads/2016/03/300-DD.jpg')

        fishtanks = [Ten, Twenty, Thirty, Forty, Fifty_Five, Seventy, HundredAndFifty,THREEHUNDRED]

        print('creating Users...')

        user1 = User(username='Chris', email='Chris@example.com')
        user2 = User(username='Justin', email='Justin@example.com')
        user3 = User(username='Nate', email= 'Nate@example.com')
        user4 = User(username='Ayah', email='Ayah@example.com')
        user5 = User(username='Mathew', email='Mathew@example.com')
        user6 = User(username='Robert', email='Robert@example.com')
        user7 = User(username='Isabella', email='Isabella@example.com')
        user8 = User(username='Areeb', email='Areeb@example.com')
        user9 = User(username='Nickita', email='Nickita@example.com')
        user10 = User(username='Keino', email='Keino@example.com')

        users = [user1, user2, user3, user4, user5, user6, user7, user8, user9, user10]
        for user in users:
            user.password_hash = bcrypt.generate_password_hash(user.username + 'password').decode('utf-8')
        # user.password_hash = user.username + 'password'
        #We may need the code above for later use    
        print('Creating Reviews...')

        reviews = [
            Review(comment = 'This fish is pretty dope', rating = 5, fishtank_id = 1),
            Review(comment ='Loved this fishtank!', rating='4', fishtank_id=2),
            Review(comment ='Disappointed with the quality of these fish.', rating='2', fish_id=3),
            Review(comment ='This fishtank is amazing!', rating='5', fishtank_id=1),
            Review(comment ='Decent selection of fish.', rating='3', fish_id=2),
            Review(comment ='Very happy with my purchase.', rating='4', fishtank_id=3)
        ]


        db.session.add_all(fishtanks)
        db.session.add_all(fishes)
        db.session.add_all(users)
        db.session.add_all(reviews)
        db.session.commit()