"""empty message

Revision ID: 059410d20564
Revises: fbea82d15037
Create Date: 2023-04-17 22:30:56.898713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059410d20564'
down_revision = 'fbea82d15037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
