"""empty message

Revision ID: 744ad545bf64
Revises: 
Create Date: 2023-04-05 10:34:08.790094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744ad545bf64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('tank_size', sa.String(), nullable=True),
    sa.Column('water_preference', sa.String(), nullable=True),
    sa.Column('temperature_preference', sa.String(), nullable=True),
    sa.Column('aggressiveness', sa.String(), nullable=True),
    sa.Column('tank_mate_compatibility', sa.String(), nullable=True),
    sa.Column('life_expectancy', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fishtanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_name', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fish_species_tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('fishtank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], name=op.f('fk_fish_species_tanks_fish_id_fishes')),
    sa.ForeignKeyConstraint(['fishtank_id'], ['fishtanks.id'], name=op.f('fk_fish_species_tanks_fishtank_id_fishtanks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('fishtank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fishes.id'], name=op.f('fk_reviews_fish_id_fishes')),
    sa.ForeignKeyConstraint(['fishtank_id'], ['fishtanks.id'], name=op.f('fk_reviews_fishtank_id_fishtanks')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('fish_species_tanks')
    op.drop_table('users')
    op.drop_table('fishtanks')
    op.drop_table('fishes')
    # ### end Alembic commands ###
