"""empty message

Revision ID: c838ac93f222
Revises: 744ad545bf64
Create Date: 2023-04-05 10:35:08.205885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c838ac93f222'
down_revision = '744ad545bf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishes', schema=None) as batch_op:
        batch_op.drop_column('species')

    # ### end Alembic commands ###
