"""empty message

Revision ID: fbea82d15037
Revises: 9f903062cec3
Create Date: 2023-04-17 22:07:12.218936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbea82d15037'
down_revision = '9f903062cec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishes', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
